apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nic-feature-discovery-ds
  namespace: kube-system
  labels:
    tier: node
    app: nic-feature-discovery
    name: nic-feature-discovery
spec:
  selector:
    matchLabels:
      name: nic-feature-discovery
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: nic-feature-discovery
        name: nic-feature-discovery
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      containers:
        - name: nic-feature-discovery
          image: ghcr.io/mellanox/nic-feature-discovery:latest
          command: [ "/nic-feature-discovery" ]
          args:
            - --v=0
            - --logging-format=json
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: features-dir
              mountPath: /etc/node-feature-discovery/features.d
      terminationGracePeriodSeconds: 10
      volumes:
        - name: features-dir
          hostPath:
            path: /etc/node-feature-discovery/features.d
            type: DirectoryOrCreate
