name: "Build, Test, Lint"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      install-task: true
      build-command: task build
      lint-command: task lint
      test-command: task test
      coverage-file: nic-feature-discovery.cover
      validate-command: |
        go mod tidy
        git diff --exit-code
  build-image:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/image-build-reusable.yml@main
